name: PHP Composer

on:
#  push:
#    branches: [ workflows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install Composer dependencies
      run: composer install

    - name: Build a package
      run: ./builder.sh -t pack
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}

    - uses: ./.github/workflows/upload.yml
      # secrets: inherit

